[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bubblegum_cpi = "F7uCq1ZAShY1bjMiMMwRkMsCdpgTgwhYtaQorHE9snca"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypairs/creator.json"

[scripts]
bubblegum = "DEBUG='log:*,compute:*,txId:*' yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/bubblegum-cpi.ts"